export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const PROFILE_ADD_START = 'PROFILE_ADD_START';
export const PROFILE_ADD_SUCCESS = 'PROFILE_ADD_SUCCESS';
export const PROFILE_ADD_FAILURE = 'PROFILE_ADD_FAILURE';
