export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const PROFILE_ADD_START = 'PROFILE_ADD_START';
export const PROFILE_ADD_SUCCESS = 'PROFILE_ADD_SUCCESS';
export const PROFILE_ADD_FAILURE = 'PROFILE_ADD_FAILURE';

export const REQUEST_ADD_START = 'REQUEST_ADD_START';
export const REQUEST_ADD_SUCCESS = 'REQUEST_ADD_SUCCESS';
export const REQUEST_ADD_FAILURE = 'REQUEST_ADD_FAILURE';

export const FLIGHT_START = 'FLIGHT_START';
export const FLIGHT_SUCCESS = 'FLIGHT_SUCCESS';
export const FLIGHT_FAILURE = 'FLIGHT_FAILURE';

export const AIRPORT_ADD_START = 'AIRPORT_ADD_START';
export const AIRPORT_ADD_SUCCESS = 'AIRPORT_ADD_SUCCESS';
export const AIRPORT_ADD_FAILURE = 'AIRPORT_ADD_FAILURE';
